"""use firebase authentication

Revision ID: 38a226de78ec
Revises: a4220869e8f6
Create Date: 2026-09-23 16:15:59.595449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "38a226de78ec"
down_revision: str | Sequence[str] | None = "a4220869e8f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    user_count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM users")).scalar_one()
    if user_count:
        raise RuntimeError(
            "Firebase authentication migration requires an empty users table. "
            "Migrate existing identities before applying it."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("firebase_uid", sa.String(length=128), nullable=False))
    op.create_index("uq_users_firebase_uid", "users", ["firebase_uid"], unique=True)
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index("uq_users_firebase_uid", table_name="users")
    op.drop_column("users", "firebase_uid")
    # ### end Alembic commands ###
