"""create identity tables

Revision ID: a4220869e8f6
Revises:
Create Date: 2026-09-23 13:41:59.437004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a4220869e8f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = sa.Enum(
    "system_admin",
    "clinic_manager",
    "managing_dentist",
    "dentist",
    "clinic_staff",
    "technician",
    name="role_code",
)


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinics",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinics")),
    )
    op.create_index(
        "uq_clinics_code_lower", "clinics", [sa.literal_column("lower(code)")], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "user_role_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role IN ('system_admin', 'technician') AND clinic_id IS NULL) OR "
            "(role IN ('clinic_manager', 'managing_dentist', 'dentist', 'clinic_staff') "
            "AND clinic_id IS NOT NULL)",
            name=op.f("ck_user_role_assignments_role_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
            name=op.f("fk_user_role_assignments_clinic_id_clinics"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_role_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_assignments")),
    )
    op.create_index(
        op.f("ix_user_role_assignments_clinic_id"),
        "user_role_assignments",
        ["clinic_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_role_assignments_clinic_role",
        "user_role_assignments",
        ["clinic_id", "role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_role_assignments_user_id"), "user_role_assignments", ["user_id"], unique=False
    )
    op.create_index(
        "uq_user_role_assignment_clinic",
        "user_role_assignments",
        ["user_id", "role", "clinic_id"],
        unique=True,
        postgresql_where=sa.text("clinic_id IS NOT NULL"),
    )
    op.create_index(
        "uq_user_role_assignment_global",
        "user_role_assignments",
        ["user_id", "role"],
        unique=True,
        postgresql_where=sa.text("clinic_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_user_role_assignment_global",
        table_name="user_role_assignments",
        postgresql_where=sa.text("clinic_id IS NULL"),
    )
    op.drop_index(
        "uq_user_role_assignment_clinic",
        table_name="user_role_assignments",
        postgresql_where=sa.text("clinic_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_user_role_assignments_user_id"), table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_clinic_role", table_name="user_role_assignments")
    op.drop_index(op.f("ix_user_role_assignments_clinic_id"), table_name="user_role_assignments")
    op.drop_table("user_role_assignments")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index("uq_clinics_code_lower", table_name="clinics")
    op.drop_table("clinics")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
