export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "auth.session_created": "Oturum açıldı",
  "auth.session_ended": "Oturum kapatıldı",
  "account.password_changed": "Parola değiştirildi",
  "clinic.created": "Klinik oluşturuldu",
  "clinic.updated": "Klinik güncellendi",
  "clinic.deactivated": "Klinik pasifleştirildi",
  "clinic.reactivated": "Klinik etkinleştirildi",
  "user.created": "Kullanıcı oluşturuldu",
  "user.updated": "Kullanıcı güncellendi",
  "user.deactivated": "Kullanıcı pasifleştirildi",
  "user.reactivated": "Kullanıcı etkinleştirildi",
  "user.role_assigned": "Rol atandı",
  "user.role_changed": "Rol değiştirildi",
  "user.role_deactivated": "Rol pasifleştirildi",
  "user.role_reactivated": "Rol etkinleştirildi",
  "user.clinic_assigned": "Klinik atandı",
  "user.clinic_deactivated": "Klinik ataması pasifleştirildi",
  "user.clinic_reactivated": "Klinik ataması etkinleştirildi",
  "case.created": "Vaka oluşturuldu",
  "case.updated": "Vaka bilgileri güncellendi",
  "case.submitted": "Vaka yönetici onayına gönderildi",
  "case.cancelled": "Vaka iptal edildi",
  "case.manager_approved": "Tarama yönetici tarafından onaylandı",
  "case.manager_revision_requested": "Tarama düzeltmesi istendi",
  "case.manager_rejected": "Vaka kesin reddedildi",
  "case.design_submitted": "Tasarım hekim onayına gönderildi",
  "case.design_approved": "Tasarım hekim tarafından onaylandı",
  "case.design_revision_requested": "Tasarım düzeltmesi istendi",
  "case.production_started": "Üretim başlatıldı",
  "case.production_completed": "Üretim tamamlandı",
  "case.shipped": "Ürün kargoya verildi",
  "case.delivery_confirmed": "Şube teslimi doğrulandı",
  "case.return_received": "İade laboratuvara ulaştı",
  "case.reproduction_requested": "Yeniden üretim istendi",
  "case.created_from_return": "İadeden yeni vaka oluşturuldu",
  "case.rescan_requested": "Yeni tarama istendi",
  "case.transfer_requested": "Vaka devri istendi",
  "case.transfer_accepted": "Vaka devri kabul edildi",
  "case.transfer_rejected": "Vaka devri reddedildi",
  "case.file_upload_started": "Dosya yüklemesi başlatıldı",
  "case.file_uploaded": "Dosya yüklendi",
  "case.file_upload_failed": "Dosya yüklemesi başarısız oldu",
  "case.file_upload_expired": "Dosya yükleme süresi doldu",
  "case.file_downloaded": "Dosya indirildi",
  "case.file_previewed": "Dosya önizlendi",
  "case.file_mesh_validated": "Dosya doğrulandı",
  "notification.dismissed": "Bildirim okundu",
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  clinic: "Klinik",
  user: "Kullanıcı",
  user_role_assignment: "Rol ataması",
  user_clinic_assignment: "Klinik ataması",
  case: "Vaka",
  case_file_version: "Vaka dosyası",
  case_upload_session: "Dosya yüklemesi",
  case_transfer: "Vaka devri",
  notification: "Bildirim",
};
